# Extensions
NUMPY_ARRAY_EXTENSION = "npy"
DICOM_FILE_EXTENSION = "dcm"
JSON_FILE_EXTENSTION = "json"
TXT_FILE_EXTENSION = "txt"
GZ_FILE_EXTENSION = "gz"
MHA_FILE_EXTENSION = "mha"
MHD_FILE_EXTENSION = "mhd"
NRRD_FILE_EXTENSION = "nrrd"
NIFTI_FILE_EXTENSION = "nii"
CONFIG_FILE_EXTENSION = "cfg"
PKL_FILE_EXTENSION = "pkl"
BDF_FILE_EXTENSION = "bdf"
FTPP_FILE_EXTENSION = "dat"
TOPAS_BIN_EXTENSION = "bin"
TOPAS_BIN_HEADER_EXTENSION = "binheader"

# Numeric constants
CT_HU_AIR = -1000
CT_HU_BONE = 3000
EPS = 1e-10

# DEFAULTS
DEFAULT_DEVICE = "cuda:0"




